services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-app
    environment:
      - NODE_ENV=production
      - PORT=3005
    ports:
      - "3005:3005"
    restart: unless-stopped
    networks:
      - tanstack-network

networks:
  tanstack-network:
    driver: bridge
